<h1>Vehicle Category View</h1>
<?php echo $this->vehicleCategoryNav(); ?>
<style>
.sl-vehicle-container {
    display: inline-block;
    position: relative;
    margin: 0;
    margin-bottom: 25px;
    padding: 0;
    height: auto;
    font-family: Lato, Helvetica, Arial, sans-serif;
}
.sl-vehicle-container img {
    vertical-align: middle;
}

.sl-price {
    position: absolute;
    top: 10px;
    left: 10px;
    padding: 10px 15px;
    background: #ffffff;
    font-size: 16px;
    border-radius: 3px;
}
.sl-vehicle-details {
    margin: 0;
    padding: 0;
    border-left: 1px solid #f2f1f1;
    border-right: 1px solid #f2f1f1;
    border-bottom: 1px solid #f2f1f1;
}
.sl-vehicle-details h1 {
    margin: 0;
    padding-top: 10px;
    padding-left: 15px;
    padding-right: 10px;
    line-height: 26px;
    font-size: 20px!important;
}
.sl-vehicle-details h1 a {
    margin: 0;
    padding: 0;
    text-decoration: none;
    color: #666464;
}

.sl-vehicle-details p {
    margin: 0;
    padding-top: 10px;
    padding-left: 15px;
    padding-right: 10px;
    padding-bottom: 15px;
    font-size: 15px;
}
.sl-vehicle-details p a {
    margin: 0;
    padding: 0;
    text-decoration: none;
    color: #777777;
}

</style>
<div class="container">
    <div class="row">
        <div class="col-sm-6 col-md-4">
            <div class="sl-vehicle-container">
                <a href="#"><img class="img-responsive" src="/images/vehicles/58_400.jpg" alt="Vehicle"></a>
                <span class="sl-price">&pound;15,500</span>
                <div class="sl-vehicle-details">
                    <h1><a href="#">2009 Concorde Charisma 890G Smart Garage</a></h1>
                    <p><a href="#">Two owners from new, 17,000 miles with full service history. An abundance of space is very apparent to the interior, to include a very large bathroom, plus a fixed island bed allowing movement around both sides.</a></p>
                </div>
            </div>
        </div>

        <div class="col-sm-6 col-md-4">
            <div class="sl-vehicle-container">
                <a href="#"><img class="img-responsive" src="/images/vehicles/58_400.jpg" alt="Vehicle"></a>
                <span class="sl-price">&pound;15,500</span>
                <div class="sl-vehicle-details">
                    <h1><a href="#">2009 Concorde Charisma 890G Smart Garage</a></h1>
                    <p><a href="#">Two owners from new, 17,000 miles with full service history. An abundance of space is very apparent to the interior, to include a very large bathroom, plus a fixed island bed allowing movement around both sides.</a></p>
                </div>
            </div>
        </div>
        <div class="clearfix visible-sm-block"></div>

        <div class="col-sm-6 col-md-4">
            <div class="sl-vehicle-container">
                <a href="#"><img class="img-responsive" src="/images/vehicles/58_400.jpg" alt="Vehicle"></a>
                <span class="sl-price">&pound;15,500</span>
                <div class="sl-vehicle-details">
                    <h1><a href="#">2009 Concorde Charisma 890G Smart Garage</a></h1>
                    <p><a href="#">Two owners from new, 17,000 miles with full service history. An abundance of space is very apparent to the interior, to include a very large bathroom, plus a fixed island bed allowing movement around both sides.</a></p>
                </div>
            </div>
        </div>
        <div class="clearfix visible-md-block"></div>

        <div class="col-sm-6 col-md-4">
            <p>Box 4</p>
        </div>
        <div class="clearfix visible-sm-block"></div>
        <div class="clearfix visible-lg-block"></div>

        <div class="col-sm-6 col-md-4">
            <p>Box 5</p>
        </div>
    </div>
</div>
