<h1>Vehicle Category View</h1>
<?php echo $this->vehicleCategoryNav(); ?>
<style>
.sl-vehicle-container {
    display: inline-block;
    /*max-width: 340px;*/
    position: relative;
    margin: 0;
    margin-bottom: 25px;
    padding: 0;
    height: auto;
    font-family: Lato, Helvetica, Arial, sans-serif;
}
.sl-vehicle-container img {
    vertical-align: middle;
}

.sl-price {
    position: absolute;
    top: 10px;
    left: 10px;
    padding: 10px 15px;
    background: #ffffff;
    font-size: 16px;
    border-radius: 3px;
}
.sl-vehicle-details {
    margin: 0;
    padding: 0;
    border-left: 1px solid #f2f1f1;
    border-right: 1px solid #f2f1f1;
    border-bottom: 1px solid #f2f1f1;
}
.sl-vehicle-details h1 {
    margin: 0;
    padding-top: 10px;
    padding-left: 15px;
    padding-right: 10px;
    line-height: 26px;
    font-size: 20px!important;
}
.sl-vehicle-details h1 a {
    margin: 0;
    padding: 0;
    text-decoration: none;
    color: #666464;
}

.sl-vehicle-details p {
    margin: 0;
    padding-top: 10px;
    padding-left: 15px;
    padding-right: 10px;
    padding-bottom: 15px;
    font-size: 15px;
}
.sl-vehicle-details p a {
    margin: 0;
    padding: 0;
    text-decoration: none;
    color: #777777;
}
.sl-vehicle-container .label {
    position:absolute;
    left: -4px;
    top: -3px
}
</style>

<br>
    <br><br>

<div class="container">

    <div class="row">
        <?php $i = 1; ?>
        <?php foreach ($vehiclesMap as $vi) : ?>
        <?php $v = $vi['vehicleObj']; ?>
        <?php $imageId = $vi['image_id']; ?>
        <div class="col-sm-6 col-md-4 col-lg-4">
            <div class="sl-vehicle-container">
                <a href="/<?php echo $this->escapeHtmlAttr($v->getUrl()); ?>"><img class="img-responsive" src="/images/vehicles/<?php echo $this->escapeHtml($imageId); ?>_340.jpg" alt="<?php echo $this->escapeHtmlAttr($v->getPageTitle()); ?>"></a>
                <span class="sl-price"><?php echo $this->price($v->getPrice(), 'GBP', ['decimal_places' => 0]); ?></span>

                <?php if ($v->getSold() === true) : ?>
                <span class="label label-danger" style="font-size: 16px;" >SOLD</span>
                <?php endif ?>

                <div class="sl-vehicle-details">
                    <h1><a href="/<?php echo $this->escapeHtmlAttr($v->getUrl()); ?>"><?php echo $this->escapeHtml($v->getPageTitle()); ?></a></h1>
                    <p><a href="/<?php echo $this->escapeHtmlAttr($v->getUrl()); ?>"><?php echo $this->escapeHtml($v->getMetaDesc()); ?></a></p>
                </div>
            </div>
        </div>
        <?php if (($i % 2) === 0): ?>
        <div class="clearfix visible-sm-block"></div>
        <?php endif ?>
        <?php if (($i % 3) === 0): ?>
        <div class="clearfix visible-md-block visible-lg-block"></div>
        <?php endif ?>
        <?php $i++; ?>
        <?php endforeach ?>
    </div>
</div>
