<div class="container">
    <div class="row">
        <?php $i = 1; ?>
        <?php foreach ($vehiclesMap as $vi) : ?>
        <?php $v = $vi['vehicleObj']; ?>
        <?php $imageId = $vi['image_id']; ?>
        <div class="col-sm-6 col-md-4 col-lg-4">
            <div class="sl-vehicle-container">
                <a href="/<?php echo $this->escapeHtmlAttr($v->getUrl()); ?>"><img class="img-responsive" src="/images/vehicles/<?php echo $this->escapeHtml($imageId); ?>_360.jpg" alt="<?php echo $this->escapeHtmlAttr($v->getPageTitle()); ?>"></a>
                <span class="sl-price"><?php echo $this->price($v->getPrice(), 'GBP', ['decimal_places' => 0]); ?></span>

                <?php if ($v->getSold() === true) : ?>
                <span class="label label-danger" style="font-size: 16px;" >SOLD</span>
                <?php endif ?>

                <div class="sl-vehicle-details">
                    <h1><a href="/<?php echo $this->escapeHtmlAttr($v->getUrl()); ?>"><?php echo $this->escapeHtml($v->getPageTitle()); ?></a></h1>
                    <p><a href="/<?php echo $this->escapeHtmlAttr($v->getUrl()); ?>"><?php echo $this->escapeHtml($v->getMetaDesc()); ?></a></p>
                </div>
            </div>
        </div>
        <?php if (($i % 2) === 0): ?>
        <div class="clearfix visible-sm-block"></div>
        <?php endif ?>
        <?php if (($i % 3) === 0): ?>
        <div class="clearfix visible-md-block visible-lg-block"></div>
        <?php endif ?>
        <?php $i++; ?>
        <?php endforeach ?>
    </div>
</div>
