<?php if ($page !== null) : ?>
<?php $this->vehicleCategoryNav()->setUrl($url); ?>
<?php $this->headMeta()->setMetaKeywords($page->getMetaKeywords())
                       ->setMetaDescription($page->getMetaDesc())
                       ->setTitle($page->getPageTitle()); ?>


<div class="row">
<div class="col-lg-8">
    <div class="sl-inner-whiteboard">
        <?php echo $page->getPageHtml(); ?>
    </div>
</div>
<div class="col-lg-4">

    <div class="sl-vehicle-featured-box">
    <div class="sl-vehicle-container-header">
        FEATURED VEHICLE
    </div>
    <div class="sl-vehicle-container">
        <div class="sl-vehicle-details">
            <h1><a href="/<?php echo $this->escapeHtmlAttr($fv['url']); ?>"><?php echo $this->escapeHtml($fv['page_title']); ?></a></h1>
            <h2><?php echo $this->price($fv['price'], 'GBP', ['decimal_places' => 0]); ?></h2>
        </div>
        <a href="/<?php echo $this->escapeHtmlAttr($fv['url']); ?>"><img class="img-responsive" src="/images/vehicles/<?php echo $this->escapeHtml($fv['image_id']); ?>_360.jpg" alt="<?php echo $this->escapeHtmlAttr($fv['page_title']); ?>"></a>
        <!--<span class="sl-price"><?php echo $this->price($fv['price'], 'GBP', ['decimal_places' => 0]); ?></span>-->
        <?php if ($fv['sold'] === '1') : ?>
        <span class="label label-danger" style="font-size: 16px;" >SOLD</span>
        <?php endif ?>
        <div class="sl-vehicle-details">
            <p><a href="/<?php echo $this->escapeHtmlAttr($fv['url']); ?>"><?php echo $this->escapeHtml($fv['meta_desc']); ?></a></p>
        </div>
    </div>

</div>
</div>
</div>

<?php endif ?>
