<?php $this->headMeta()->setMetaKeywords($vehicle->getMetaKeywords())
                       ->setMetaDescription($vehicle->getMetaDesc())
                       ->setTitle($vehicle->getPageTitle()); ?>
<?php echo $this->vehicleCategoryNav(); ?>
<?php //var_dump($images); ?>
<style>
body {
    font-size: 16px;
}
.carousel-inner > .item > img {
    margin: 0 auto;
}
.carousel-control.left,
.carousel-control.right {
    background-image: none
}
#carousel-example-generic {
    margin: 0;
    padding-left: 0px;
    padding-right: 0px;
}

.sl-vehicle-features {
    padding-left: 0px;
    padding-right: 0px;
}
div.sl-vehicle-features ul {
    list-style: none;
    padding-left: 0px;
    line-height: 1.7em;
}
@media (min-width: 992px) {
    .sl-summary-heading {
        margin-top: -3px;
    }
    .sl-vehicle-features {
        padding-left: 40px;
    }
}
@media (min-width: 992px) {
    .sl-vehicle-main {
        padding-top: 20px;
    }
}
</style>
<div class="container">

<h3><?php echo $this->escapeHtml($vehicle->getPageTitle()); ?></h3>

<?php if ($hasImages) : ?>
<div id="carousel-example-generic" class="carousel slide col-md-7" data-ride="carousel" data-interval="false" data-wrap="false">

<!-- Indicators -->
<ol class="carousel-indicators">
<?php foreach ($images as $i) : ?>
<?php $priority = $i->getPriority(); ?>
    <li data-target="#carousel-example-generic" data-slide-to="<?php echo $this->escapeHtmlAttr($priority - 1); ?>"<?php echo ($priority === 1) ? ' class="active"' : '' ?>></li>
<?php endforeach ?>
</ol>

<!-- Wrapper for slides -->
<div class="carousel-inner" role="listbox">
<?php foreach ($images as $i) : ?>
<?php $priority = $i->getPriority(); ?>
    <div class="item<?php echo ($priority === 1) ? ' active' : '' ?>">
        <img class="img-responsive" src="/images/vehicles/<?php echo $this->escapeHtmlAttr($i->getImageId()) ?>_720.jpg" alt="...">
    </div>
<?php endforeach ?>
</div>

<!-- Controls -->
<a class="left carousel-control" href="#carousel-example-generic" role="button" data-slide="prev">
  <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
  <span class="sr-only">Previous</span>
</a>
<a class="right carousel-control" href="#carousel-example-generic" role="button" data-slide="next">
  <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
  <span class="sr-only">Next</span>
</a>
</div>
<?php endif ?>

<div class="col-md-5 sl-vehicle-features">
    <!--<h5 class="sl-summary-heading"><?php //echo $this->escapeHtml($vehicle->getMetaDesc()); ?></h5>-->
    <ul>
        <li><span class="glyphicon glyphicon-ok success"></span> 4 Berth</li>
        <li><span class="glyphicon glyphicon-ok success"></span> Fixed Island Bed</li>
        <li><span class="glyphicon glyphicon-ok success"></span> U Shaped Lounge</li>
        <li><span class="glyphicon glyphicon-ok success"></span> Separate Shower</li>
        <li><span class="glyphicon glyphicon-ok success"></span> Solar Panel</li>
    </ul>
    <p><?php echo $this->escapeHtml($vehicle->getMetaDesc()); ?></p>
</div>

<div class="clearfix visible-md-block visible-lg-block"></div>

<div class="sl-vehicle-main">
    <?php echo $vehicle->getPageHtml(); ?>
</div>

</div>

<script>
$(function() {
    $('.carousel').carousel();
});
