<h2>Markdown Editor</h2>

<p class="lead">Advanced markdown editor</p>

<div class="container">
<form class="sl-form form-horizontal" method="post" action="/admin/markdown-editor/edit">
<?php
    $id = $form->get('id');
    echo $this->formHidden($id);
?>

<div class="form-group">
<label for="markdown">Markdown</label>
<?php
    $markdown = $form->get('markdown')->setAttribute('class', ['form-control', 'sl-markdown-advanced'])
                                      ->setAttribute('rows', '12');
    echo $this->formTextarea($markdown);
    echo $this->formElementErrors($markdown);
?>
</div>

<div class="form-group">
    <button class="btn-lg btn-success">Save</button>
</div>
</form>
</div>
