<h2>Upload Images</h2>
<p class="lead">Be sure to choose a collection from the select box before selecting your image for upload.</p>

<div class="container">
<form class="sl-form form-horizontal" enctype="multipart/form-data" method="post" action="/image-uploader">
<input type="hidden" name="MAX_FILE_SIZE" value="8388608">

<div class="form-group">
<label for="collection-id">Collection</label>
<?php
    $collectionId = $form->get('collection-id')->setAttribute('class', 'form-control');;
    echo $this->formSelect($collectionId);
    echo $this->formElementErrors($collectionId);
?>
</div>

<div class="form-group">
<label for="filename">Choose Files</label>
<?php
    $filename = $form->get('filename')->setAttribute('multiple', 'multiple')
                                      ->setAttribute('class', 'form-control')
                                      ->setAttribute('accept', 'image/jpeg');
    echo $this->formFile($filename);
    echo $this->formElementErrors($filename);
?>
<p class="help-block">Within the file browser window use the <kbd>&#x2318;</kbd> (command key) to select multiple files</p>
</div>

<div class="form-group">
<button class="btn-lg btn-success">Upload</button>
</div>
</div>

<script>
$(function() {
  $('#nav-upload-images').addClass('active');
});
</script>
