<h2>Vehicles</h2>
<table class="table table-striped table-condensed">
<tr class="info">
    <th>Page Title / Link</th>
    <th>Collection Tag</th>
    <th>Last Modified</th>
    <th>Status</th>
    <th class="text-right">Price</th>
    <th>&nbsp;</th>
</tr>
<?php foreach ($vehiclesMap as $categoryName => $vehicleAndCollections) : ?>
<tr class="info"><th colspan="8"><?php echo $this->vehicleType($categoryName); ?></th></tr>
<?php foreach ($vehicleAndCollections as $vehicleAndCollection) : ?>
<?php $v = $vehicleAndCollection['vehicleObj']; ?>
<?php $c = $vehicleAndCollection['collection']; ?>
<?php
$vehicleId = $v->getVehicleId();
$visible = $v->getVisible();
?>
<tr>
    <td><?php echo $this->escapeHtml($v->getPageTitle()); ?><br><kbd class="alert-warning"><a href="<?php echo $this->escapeHtmlAttr('/' . $v->getUrl()); ?>" target="_blank"><span class="glyphicon glyphicon-link"></span> <?php echo $this->escapeHtml($v->getUrl()); ?></a></kbd></td>
    <td><kbd class="alert-success"><span class="glyphicon glyphicon-tag"></span> <?php echo $this->escapeHtml($c['tagname']); ?></kbd></td>
    <td><?php echo $this->showDateTime($v->getModified(), $localTimeZone); ?></td>
    <td><?php echo ($visible === true) ? '<kbd class="alert-success">VISIBLE</kbd>' : '<kbd class="alert-danger">INVISIBLE</kbd>'; ?></td>
    <td class="text-right"><?php echo $this->price($v->getPrice(), 'GBP', ['decimal_places' => 0]); ?><?php echo ($v->getSold() === true) ? ' <br><kbd class="alert-danger">SOLD</kbd> ' : ''; ?></td>
    <td>
        <ul class="nav nav-pills">
            <li role="presentation"><a href="/add-edit-vehicle/<?php echo $this->escapeHtml($vehicleId); ?>"><span class="glyphicon glyphicon-edit"></span> Edit</a></li>
        </ul>
    </td>
</tr>
<?php endforeach; ?>
<?php endforeach; ?>
</table>

<script>
$(function() {
  $('#nav-vehicles').addClass('active');
});
</script>
