<table class="table table-striped table-hover">
<tr class="info">
    <th>Page Title</th>
    <th>Last Modified</th>
    <th class="text-right">Price</th>
    <th>&nbsp;</th>
</tr>
<?php foreach ($vehiclesMap as $categoryName => $subcategory) : ?>
<tr class="info"><th colspan="8"><?php echo $this->escapeHtml($categoryName); ?></th></tr>
<?php foreach ($subcategory as $v) : ?>
<?php //var_dump($v); ?>
<?php
$vehicleId = $v->getVehicleId();
$visible = $v->getVisible();
?>
<tr<?php echo ($visible === false) ? ' class="danger"' : '' ?>>
    <td><?php echo $this->escapeHtml($v->getPageTitle()); ?><br><kbd class="alert-warning"><a href="#"><span class="glyphicon glyphicon-link"></span> <?php echo $this->escapeHtml($v->getUrl()); ?></a></kbd></td>
    <td><?php echo $this->showDateTime($v->getModified(), $localTimeZone); ?></td>
    <td class="text-right"><?php echo $this->price($v->getPrice(), 'GBP', ['decimal_places' => 0]); ?><?php echo ($v->getSold() === true) ? '<br><kbd class="alert-danger">SOLD</kbd> ' : ''; ?></td>
    <td>
        <ul class="nav nav-pills">
            <li role="presentation"><a href="/add-edit-vehicle/<?php echo $this->escapeHtml($vehicleId); ?>"><span class="glyphicon glyphicon-edit"></span> Edit</a></li>
            <li role="presentation"><a href="#"><span class="glyphicon glyphicon-eye-open"></span> View</a></li>
        </ul>
    </td>
</tr>
<?php endforeach; ?>
<?php endforeach; ?>
</table>

<button type="button" class="btn btn-default" data-toggle="tooltip" data-placement="top" title="Tooltip on left">Tooltip on left</button>
<script>
$(function () {
  $('[data-toggle="tooltip"]').tooltip()
})
</script>
