<h2>Pages</h2>
<p class="lead">Manage your page content</p>
<table class="table table-striped table-hover">
<tr class="info">
    <th>Name</th>
    <th>Page Url</th>
    <th>Date added</th>
    <th>Last modified</th>
    <th>&nbsp;</th>
</tr>
<?php foreach ($pages as $p) : ?>
<?php $pageId = $p->getPageId(); ?>
<tr>
    <td><?php echo $this->escapeHtml($p->getName()); ?></td>
    <td><a href="<?php echo $this->escapeHtmlAttr('/' . $p->getUrl()); ?>"><kbd class="alert-warning"><span class="glyphicon glyphicon-link"></span> <?php echo $this->escapeHtml($p->getUrl()); ?></kbd></a></td>
    <td><?php echo $this->showDateTime($p->getCreated(), $localTimeZone); ?></td>
    <td><?php echo $this->showDateTime($p->getModified(), $localTimeZone); ?></td>
    <td>
        <ul class="nav nav-pills">
            <li role="presentation"><a href="/admin/edit-page/<?php echo $this->escapeHtml($pageId); ?>"><span class="glyphicon glyphicon-edit"></span> Edit</a></li>
            <li role="presentation" class="dropdown">
                <a class="dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false"> <span class="glyphicon glyphicon-trash"></span> <span class="caret"></span> Del</a>
                <ul class="dropdown-menu">
                    <li role="presentation"><a href="/admin/delete-page/<?php echo $this->escapeHtml($pageId); ?>">Confirm</a></li>
                </ul>
            </li>
        </ul>
    </td>
</tr>
<?php endforeach; ?>
</table>

<script>
$(function() {
  $('#nav-list-pages').addClass('active');
});
</script>
