<h2>Pages</h2>
<p class="lead">Manage your page content</p>
<table class="table table-striped table-hover">
<tr class="info">
    <th>Name</th>
    <th>Page Url</th>
    <th>Date added</th>
    <th>Last modified</th>
    <th>Change Ordering</th>
</tr>

<?php foreach (['pages_top', 'pages_main', 'pages_footer'] as $section) : ?>
<?php $layoutPosition = substr($section, strpos($section, "_") + 1); ?>
<tr class="info">
    <th colspan="4"><?php echo $this->escapeHtml($this->pageLayoutPosition($layoutPosition)); ?> <span class="badge"><?php echo $this->escapeHtml(count($$section)); ?></span></th>
    <th>
        <ul class="nav nav-pills">
            <li role="presentation"><a href="/admin/page-ordering/<?php echo $this->escapeHtml($layoutPosition); ?>">Ordering <span class="glyphicon glyphicon-sort"></span></a></li>
        </ul>
    </th>
</tr>
<?php foreach ($$section as $p) : ?>
<?php $pageId = $p->getPageId(); ?>
<tr>
    <td><?php echo $this->escapeHtml($p->getName()); ?></td>
    <td><a href="<?php echo $this->escapeHtmlAttr('/' . $p->getUrl()); ?>"><kbd class="alert-warning"><span class="glyphicon glyphicon-link"></span> <?php echo $this->escapeHtml($p->getUrl()); ?></kbd></a></td>
    <td><?php echo $this->showDateTime($p->getCreated(), $localTimeZone); ?></td>
    <td><?php echo $this->showDateTime($p->getModified(), $localTimeZone); ?></td>
    <td>
        <ul class="nav nav-pills">
            <li role="presentation"><a href="/admin/edit-page/<?php echo $this->escapeHtml($pageId); ?>"><span class="glyphicon glyphicon-edit"></span> Edit</a></li>
            <li role="presentation"><a href="/admin/markdown-editor/edit/page/<?php echo $this->escapeHtml($p->getPageId()); ?>"><span class="glyphicon glyphicon-edit"></span> Markdown</a></li>
            <li role="presentation" class="dropdown">
                <a class="dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false"> <span class="glyphicon glyphicon-trash"></span> <span class="caret"></span> Del</a>
                <ul class="dropdown-menu">
                    <li role="presentation"><a href="/admin/delete-page/<?php echo $this->escapeHtml($pageId); ?>">Confirm</a></li>
                </ul>
            </li>
        </ul>
    </td>
</tr>
<?php endforeach; ?>
<?php endforeach; ?>

</table>

<script>
$(function() {
  $('#nav-list-pages').addClass('active');
});
</script>
