<h2>Add Vehicle</h2>
<p class="lead">Enter the details for your new vehicle</p>

<div class="container">
<form class="sl-form form-horizontal" method="post" action="<?php echo $this->escapeHtmlAttr($action); ?>">
<?php
    $vehicleId = $form->get('vehicle-id');
    echo $this->formHidden($vehicleId);
    echo $this->formElementErrors($vehicleId);
?>

<div class="form-group">
<label for="type">Vehicle Type</label>
<?php
    $type = $form->get('type')
                 ->setAttribute('id', 'vehicle-type')
                 ->setAttribute('class', 'form-control');
    echo $this->formSelect($type);
    echo $this->formElementErrors($type);
?>
</div>

<div class="form-group sl-short-input">
<label for="visible">Visible</label>
<?php
    $visible = $form->get('visible')->setAttribute('class', 'form-control');
    echo $this->formSelect($visible);
    echo $this->formElementErrors($visible);
?>
</div>

<div class="form-group sl-short-input">
<label for="sold">Sold</label>
<?php
    $sold = $form->get('sold')->setAttribute('class', 'form-control');
    echo $this->formSelect($sold);
    echo $this->formElementErrors($sold);
?>
</div>

<div class="form-group">
<label for="url">URL</label>
<?php
    $url = $form->get('url')->setAttribute('class', 'form-control')
                            ->setAttribute('placeholder', 'e.g. my-caravan-slug-url');
    echo $this->formText($url);
    echo $this->formElementErrors($url);
?>
</div>

<div class="form-group">
<label for="price">Price</label>
<div class="input-group sl-short-input">
    <div class="input-group-addon">&pound;</div>
    <?php
    $price = $form->get('price')->setAttribute('class', 'form-control')
                                ->setAttribute('placeholder', 'Amount');
    echo $this->formText($price);
    ?>
    <div class="input-group-addon">.00</div>
</div>
<?php echo $this->formElementErrors($price); ?>
</div>

<div class="form-group">
<label for="meta-keywords">Meta Keywords</label>
<?php
    $metaKeywords = $form->get('meta-keywords')->setAttribute('class', 'form-control')
                                               ->setAttribute('rows', '2');
    echo $this->formTextarea($metaKeywords);
    echo $this->formElementErrors($metaKeywords);
?>
</div>

<div class="form-group">
<label for="meta-desc">Meta Description</label>
<?php
    $metaDesc = $form->get('meta-desc')->setAttribute('class', 'form-control')
                                       ->setAttribute('rows', '4');
    echo $this->formTextarea($metaDesc);
    echo $this->formElementErrors($metaDesc);
?>
</div>

<div class="form-group">
<label for="page-title">Page Title</label>
<?php
    $pageTitle = $form->get('page-title')->setAttribute('class', 'form-control');
    echo $this->formText($pageTitle);
    echo $this->formElementErrors($pageTitle);
?>
</div>

<div class="form-group">
<label for="markdown">Markdown</label>
<?php
    $markdown = $form->get('markdown')->setAttribute('class', ['form-control', 'sl-markdown'])
                                      ->setAttribute('rows', '12');
    echo $this->formTextarea($markdown);
    echo $this->formElementErrors($markdown);
?>
</div>

<div class="form-group">
<button class="btn-lg btn-success">Save</button>
</div>
</form>
</div>
