

<?php //var_dump(get_defined_vars()); ?>
<?php //var_dump($this); ?>
<?php //var_dump($form); ?>


<?php //echo $this->escapeHtml('<span>'); ?>
<hr>

<form method="post" name="add-edit-vehicle">
<div class="question">
<?php
    $vehicleId = $form->get('vehicle-id');
    echo $this->formHidden($vehicleId);
?>
</div>


<div class="question">
<label for="type">Vehicle Type</label>
<?php
    $type = $form->get('type')
                 ->setAttribute('id', 'vehicle-type')
                 ->setAttribute('multiple', '')
                 ->setAttribute('class', ['a', 'b', 'c'])
                 ->setAttribute('disabled');
    echo $this->formSelect($type);
?>
</div>

<div>
<label for="visible">Visible</label>
<?php
    $visible = $form->get('visible');
    echo $this->formSelect($visible);
?>
</div>

<div>
<label for="sold">Sold</label>
<?php
    $sold = $form->get('sold');
    echo $this->formSelect($sold);
?>
</div>

<div>
<label for="url">URL</label>
<?php
    $url = $form->get('url');
    echo $this->formText($url);
?>
</div>

<div>
<label for="price">Price</label>
<?php
    $price = $form->get('price');
    echo $this->formText($price);
?>
</div>

<div class="question">
<label for="meta-keywords">Meta Keywords</label>
<?php
    $metaKeywords = $form->get('meta-keywords');
    echo $this->formTextarea($metaKeywords);
?>
</div>

<div class="question">
<label for="meta-desc">Meta Description</label>
<?php
    $metaDesc = $form->get('meta-desc');
    echo $this->formTextarea($metaDesc);
?>
</div>

<div>
<label for="page-title">Page Title</label>
<?php
    $pageTitle = $form->get('page-title');
    echo $this->formText($pageTitle);
?>
</div>

<div class="question">
<label for="markdown">Markdown</label>
<?php
    $markdown = $form->get('markdown');
    echo $this->formTextarea($markdown);
?>
</div>

<button>Save</button>
</form>

<hr>
<?php //var_dump($this); ?>
