

<?php //var_dump(get_defined_vars()); ?>
<?php //var_dump($this); ?>
<?php //var_dump($form); ?>


<?php //echo $this->escapeHtml('<span>'); ?>
<hr>

<form method="post" name="add-edit-vehicle">
<div class="question">
<label for="username">Username</label>
<?php
    $username = $form->get('username');
    echo $this->formInput($username);
?>
</div>


<div class="question">
<label for="vehicletype">Vehicle Type</label>
<?php
    $vehicleType = $form->get('vehicle-type');
    echo $this->formSelect($vehicleType);
?>
</div>

<div class="question">
<label for="meta-keywords">Meta Keywords</label>
<?php
    $metaKeywords = $form->get('meta-keywords');
    echo $this->formTextarea($metaKeywords);
?>
</div>

</form>

<hr>
<?php //var_dump($this); ?>
