<div class="container">
<form class="sl-form form-horizontal" method="post" action="/add-edit-collection">
<div>
<?php
    $collectionId = $form->get('collection-id');
    echo $this->formHidden($collectionId);
    echo $this->formElementErrors($collectionId);
?>
</div>

<div class="form-group">
<label for="name">Name</label>
<?php
    $name = $form->get('name')->setAttribute('class', 'form-control')
                              ->setAttribute('placeholder', 'Give your collection a name');
    echo $this->formText($name);
    echo $this->formElementErrors($name);
?>
</div>

<div class="form-group">
<label for="tagname">Tagname</label>
<?php
    $tagname = $form->get('tagname')->setAttribute('class', 'form-control')
                                    ->setAttribute('placeholder', 'Choose a short tagname for markdown');
    echo $this->formText($tagname);
    echo $this->formElementErrors($tagname);
?>
</div>

<div class="form-group">
<button class="btn-lg btn-success">Save</button>
</div>
</form>
</div>

<script>
$(function() {
  $('#nav-add-edit-collection').addClass('active');
});
</script>
