<h2>Collections</h2>
<p class="lead">Manage your image collections below</p>
<p>To delete a collection you must first remove all the images contained within.</p>
<table class="table table-striped table-hover">
<tr class="info">
    <!--<th>Collection Id</th>-->
    <th>Name</th>
    <th>Tag</th>
    <th># Images</th>
    <th>&nbsp;</th>
</tr>
<?php foreach ($collections as $c) : ?>
<?php $collectionId = $c->getCollectionId(); ?>
<?php $numPhotos = $photoCountMap[$collectionId]; ?>
<tr>
    <!--<td><?php echo $this->escapeHtml($collectionId); ?></td>-->
    <td><?php echo $this->escapeHtml($c->getName()); ?></td>
    <td><kbd class="alert-success"><span class="glyphicon glyphicon-tag"></span> <?php echo $this->escapeHtml($c->getTagname()); ?></kbd></td>
    <td><span class="badge"><?php echo $this->escapeHtml($numPhotos); ?></span></td>
    <!--<td><a class="disabled" href="#"><span class="glyphicon glyphicon-trash"></span></a></td>-->
    <td>
        <ul class="nav nav-pills">
            <li role="presentation"><a href="#"><span class="glyphicon glyphicon-edit"></span> Edit</a></li>
            <li role="presentation" class="dropdown<?php echo ($numPhotos > 0) ? ' disabled' : ''; ?>">
                <a class="dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false"> <span class="glyphicon glyphicon-trash"></span> <span class="caret"></span> Del</a>
                <ul class="dropdown-menu">
                    <li role="presentation"><a href="#">Confirm</a></li>
                </ul>
            </li>
            <li role="presentation"><a href="/image-uploader/<?php echo $this->escapeHtml($collectionId); ?>"><span class="glyphicon glyphicon-upload"></span> Upload</a></li>
            <li role="presentation"><a href="/view-collection/<?php echo $this->escapeHtml($collectionId); ?>"><span class="glyphicon glyphicon-eye-open"></span> View</a></li>
        </ul>
    </td>
</tr>
<?php endforeach; ?>
</table>
