<h2>Delete Vehicle</h2>
<p class="lead">Confirm the details below before confirming</p>



<div class="container">

</div>

<div class="container">
    <p>This action will delete the <?php echo $this->escapeHtml($vehicleObj->getPageTitle()); ?> vehicle and <?php echo $this->escapeHtml($collectionObj->getName()); ?> collection including all photos originals, standard size and thumbnails.</p>
    <div class="form-group">
        <form class="sl-form form-horizontal" method="post" action="<?php echo $this->escapeHtmlAttr($actionCancel); ?>">
            <button class="btn-lg btn-primary">Cancel</button>
        </form>
    </div>
    <div class="form-group">
        <form class="sl-form form-horizontal" method="post" action="<?php echo $this->escapeHtmlAttr($action); ?>">
            <input type="hidden" name="vehicle_id" value="<?php echo $this->escapeHtml($vehicleId); ?>">
            <button class="btn-lg btn-danger"">CONFIRM</button>
        </form>
    </div>
</div>
