<?php
namespace Serenity\Entity;

class VehicleFeatures
{
    const TWO_BERTH                = 'two-berth';
    const FOUR_BERTH               = 'four-berth';
    const SIX_BERTH                = 'six-berth';
    const FIXED_BED                = 'fixed-bed';
    const FIXED_ISLAND_BED         = 'fixed-island-bed';
    const U_SHAPED_LOUNGE          = 'u-shaped-lounge';
    const END_BATHROOM             = 'end-bathroom';
    const SEPARATE_SHOWER          = 'separate-shower';
    const THETFORD_TOILET          = 'thetford-toilet';
    const FRONT_LOUNGE             = 'front-lounge';
    const LED_LIGHTING             = 'led-lighting';
    const SOFT_LIGHTING            = 'soft-lighting';
    const ON_BOARD_WATER_TANK      = 'on-board-water-tank';
    const TRUMA_HEATING            = 'truma-heating';
    const ALDE_HEATING             = 'alde-eating';
    const DUAL_FUEL                = 'dual-fuel';
    const EXTRACTOR_FAN            = 'extractor-fan';
    const HEKI_SKYLIGHT            = 'heki-skylight';
    const CARBON_MONOXIDE_DETECTOR = 'carbon-monoxide-detector';
    const SMOKE_ALARM              = 'smoke-alarm';
    const PLEATED_BLINDS           = 'pleated-blinds';
    const FLYSCREENS               = 'flyscreens';
    const MICROWAVE                = 'microwave';
    const FULL_SIZED_OVEN_GRILL    = 'full-sized-over-grill';
    const MUSIC_SYSTEM             = 'music-system';
    const TELEVISION               = 'television';
    const TV_BRACKET               = 'tv-bracket';
    const ALLOY_WHEELS             = 'alloy-wheels';
    const MOTOR_MOVER              = 'motor-mover';
    const EXTERNAL_240V_SOCKET     = 'external-240v-socket';
    const SOLAR_PANEL              = 'solar-panel';
    const TV_AERIAL                = 'tv-aerial';
    const TV_POINT                 = 'tv-point';
    const ZINOX                    = 'zinox';
    const ZINOX_MEGAFRAME          = 'zinox-megaframe';
    const ISACRYL                  = 'isacryl';
    const LIGHT_ISACRYL            = 'light-isacryl';
    const ISALITE                  = 'isaLite';
    const PVC_POLYESTER            = 'pvc-polyester';
    const COATED_POLYESTER         = 'coated-polyester';
    const CARBONX                  = 'carbonx';
    const MOSQUITO_NETS            = 'mosquito-nets';
    const FRONT_DIVIDER            = 'front-divider';
    const ANNEX_250                = 'annex-250';
    const COSY_CORNER_II           = 'cosy-corner-ii';
    const CORNER_DOOR              = 'corner-door';
    const FOLD_DOWN_PANELS         = 'fold-down-panels';
    const FROSTED_WINDOW_PANELS    = 'frosted-window-panels';
    const INTEGRATED_VENTILATION   = 'integrated-ventilation';
    const EXTERNAL_MUD_FLAP        = 'external-mud-flap';
    const THREE_COLOUR             = 'three-colour';
    const TWO_COLOUR               = 'two-colour';
    const ONE_COLOUR               = 'one-colour';

    const ANNEX_220                = 'annex-220';
    const ANNEX_300                = 'annex-300';
    const IXL                      = 'ixl';
    const PRENONX                  = 'prenox';
    const TENCATE_POLYESTER        = 'tencate-polyester';
    const ACYRL                    = 'acryl';
    const LWEIGHT_FIBREGLASS       = 'lweight-fibreglass';


    public static $titles = [
        self::TWO_BERTH                => '2 Berth',
        self::FOUR_BERTH               => '4 Berth',
        self::SIX_BERTH                => '6 Berth',
        self::FIXED_BED                => 'Fixed Bed',
        self::FIXED_ISLAND_BED         => 'Fixed Island Bed',
        self::U_SHAPED_LOUNGE          => 'U Shaped Lounge',
        self::END_BATHROOM             => 'End Bathroom',
        self::SEPARATE_SHOWER          => 'Separate Shower',
        self::THETFORD_TOILET          => 'Thetford Toilet',
        self::FRONT_LOUNGE             => 'Front Lounge',
        self::LED_LIGHTING             => 'LED Lighting',
        self::SOFT_LIGHTING            => 'Soft Lighting',
        self::ON_BOARD_WATER_TANK      => 'On Board Water Tank',
        self::TRUMA_HEATING            => 'Truma Heating',
        self::ALDE_HEATING             => 'Alde Heating',
        self::DUAL_FUEL                => 'Dual Fuel',
        self::EXTRACTOR_FAN            => 'Extractor Fan',
        self::HEKI_SKYLIGHT            => 'Heki Skylight',
        self::CARBON_MONOXIDE_DETECTOR => 'CO Detector',
        self::SMOKE_ALARM              => 'Smoke Alarm',
        self::PLEATED_BLINDS           => 'Pleated Blinds',
        self::FLYSCREENS               => 'Flyscreens',
        self::MICROWAVE                => 'Microwave',
        self::FULL_SIZED_OVEN_GRILL    => 'Full Sized Oven/Grill',
        self::MUSIC_SYSTEM             => 'Music System',
        self::TELEVISION               => 'Television',
        self::TV_BRACKET               => 'TV Bracket',
        self::ALLOY_WHEELS             => 'Alloy Wheels',
        self::MOTOR_MOVER              => 'Motor Mover',
        self::EXTERNAL_240V_SOCKET     => 'External 240v Socket',
        self::SOLAR_PANEL              => 'Solar Panel',
        self::TV_AERIAL                => 'TV Aerial',
        self::TV_POINT                 => 'TV Point',
        self::ZINOX                    => 'Zinox',
        self::ZINOX_MEGAFRAME          => 'Zinox MegaFrame',
        self::ISACRYL                  => 'Isacryl',
        self::LIGHT_ISACRYL            => 'Light Isacryl',
        self::ISALITE                  => 'IsaLite',
        self::PVC_POLYESTER            => 'PVC Polyester',
        self::COATED_POLYESTER         => 'Coated Polyester',
        self::CARBONX                  => 'CarbonX',
        self::MOSQUITO_NETS            => 'Mosquito Nets',
        self::FRONT_DIVIDER            => 'Front Divider',
        self::ANNEX_250                => 'Annex 250',
        self::COSY_CORNER_II           => 'Cosy Corner II',
        self::CORNER_DOOR              => 'Corner Door',
        self::FOLD_DOWN_PANELS         => 'Removable/fold Panels',
        self::FROSTED_WINDOW_PANELS    => 'Frosted window panels',
        self::INTEGRATED_VENTILATION   => 'Integrated Ventilation',
        self::EXTERNAL_MUD_FLAP        => 'External mud flap',
        self::THREE_COLOUR             => '3 Types of Colour',
        self::TWO_COLOUR               => '2 Types of Colour',
        self::ONE_COLOUR               => '1 Type of Colour',
        self::ANNEX_220                => 'Annex 220',
        self::ANNEX_300                => 'Annex 300',
        self::IXL                      => 'IXL',
        self::PRENONX                  => 'Prenox',
        self::TENCATE_POLYESTER        => 'Tencate Polyester',
        self::ACYRL                    => 'Acrly',
        self::LWEIGHT_FIBREGLASS       => 'Lweight Fibreglass'
    ];
}
