<div class="vertical-center">

<div class="panel panel-primary center" style="max-width: 700px">
<div class="panel-heading">Sign In</div>
<div class="panel-body">


<div class="container">
<form class="sl-form form-horizontal" method="post" action="/admin-sign-in">


<div class="form-group">
<img alt="Serenity Leisure Admin" src="/images/sign-in-logo.png">
</div>

<div class="form-group">
<label for="username">Username</label>
<div class="input-group input-group-lg">
    <span class="input-group-addon"><span class="glyphicon glyphicon-user"></span></span>
    <?php
        $username = $form->get('username')->setAttribute('class', 'form-control')
                                          ->setAttribute('placeholder', 'Username');
        echo $this->formText($username);
        echo $this->formElementErrors($username);
?>
</div>
</div>

<div class="form-group">
<label for="passwd">Password</label>
<div class="input-group input-group-lg">
    <span class="input-group-addon"><span class="glyphicon glyphicon-lock"></span></span>
    <?php
    $passwd = $form->get('passwd')->setAttribute('class', 'form-control')
                                  ->setAttribute('placeholder', 'Password');
    echo $this->formText($passwd);
    ?>
</div>
<?php echo $this->formElementErrors($passwd); ?>
</form>
</div>

</div>

<div class="form-group">
<button class="btn-lg btn-success">Save</button>
</div>

</div>
</div>

</div>
