<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
    <?php echo $this->headMeta(); ?>
    <link rel="stylesheet" href="/css/bootstrap.min.css">
    <link rel="stylesheet" href="/css/bootstrap-theme.min.css">
    <link rel="stylesheet" href="/css/sl-frontend.css">
    <link href='https://fonts.googleapis.com/css?family=Open+Sans:400,700,400italic,800' rel='stylesheet' type='text/css'>
    <link href='https://fonts.googleapis.com/css?family=Bitter:400,700' rel='stylesheet' type='text/css'>
    <link href='https://fonts.googleapis.com/css?family=Lato:700,400' rel='stylesheet' type='text/css'>
    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
    <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
    <script src="/js/jquery-1.11.3.min.js"></script>
    <script src="/js/jquery-ui-1.11.4.min.js"></script>
    <script src="/js/bootstrap-3.3.5.min.js"></script>
    <script src="/js/jquery.ui.touch-punch.min.js"></script>
</head>

<body>

<div class="container">
    <div id="sl-header">
        <div class="col-sm-12 col-md-5 col-lg-5">
            <div class="visible-sm visible-xs sl-logo-spacing">
            </div>
        </div>
        <div class="col-sm-12 col-md-7 col-lg-7">
            <?php echo $this->pageNav(null); ?>

            <h1>0117 967 5577</h1>
            <p>Pioneer Unit &middot; Station Road &middot; Warmley &middot; Bristol &middot; BS30 8XH</p>
            <p>Opening Hours: Monday - Friday 8:30am - 6pm &middot; Saturday 9am - 5pm &middot; Sunday 10am - 5pm</p>
        </div>

    </div>
</div>

<div class="container">
    <?php echo $this->vehicleCategoryNav('motorhomes'); ?>

    <div id="sl-main-area">
    Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce non bibendum leo. Morbi sapien nunc, rhoncus ut quam sit amet, commodo tristique ligula. Mauris at sapien et nibh suscipit tempus. Nunc non tellus sed risus mattis euismod. In iaculis fringilla cursus. Nulla sed quam quis erat mattis vehicula at vel mi. Ut at purus elit. In aliquam vel ante vitae vestibulum. In non suscipit tortor. Pellentesque sit amet cursus sem. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Nulla aliquet cursus leo, at tristique urna volutpat nec. Sed accumsan pellentesque urna.

Mauris fringilla, lorem gravida maximus faucibus, massa augue faucibus nibh, ut tempor purus dolor id massa. Nunc facilisis at tortor at dictum. Praesent dapibus feugiat ipsum, ac accumsan risus vulputate vitae. Suspendisse id porta lectus, ac tristique libero. Etiam luctus rutrum dictum. Aenean pulvinar porttitor mauris nec lobortis. Quisque pretium, erat eu congue convallis, justo est varius eros, vel tincidunt ipsum justo non lacus. Integer finibus condimentum sem non varius. Etiam convallis purus vitae ante auctor, vel venenatis odio scelerisque. Ut feugiat metus dui, a laoreet sem malesuada at. Etiam nisl neque, posuere quis tempor at, ultrices a nisi. Proin aliquet sodales enim eget facilisis. Duis ut sagittis neque.

Etiam tempus dictum scelerisque. Etiam sed risus ipsum. Aliquam varius lorem augue, non mollis libero tempor eu. Pellentesque scelerisque urna ex. Donec lectus massa, vehicula in risus ut, mattis lacinia tellus. Vivamus luctus justo ultrices, posuere diam lobortis, dignissim ex. Nunc imperdiet ullamcorper massa eu dictum. Integer tincidunt fringilla ipsum ac fringilla. Aliquam non erat leo. Mauris ultricies rhoncus lectus, id consectetur leo volutpat ut.

Curabitur ac fermentum magna. Praesent lorem lacus, condimentum sit amet sagittis eleifend, laoreet in diam. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Donec euismod sed enim viverra varius. Mauris aliquam risus ut mi porttitor, sed mollis libero ultrices. Cras nec lacus massa. Curabitur rhoncus purus et neque pulvinar tempor. Nullam in efficitur metus. Etiam dictum lectus at volutpat lobortis. Nunc quis sapien ac odio venenatis semper. Vivamus elementum cursus quam eget consectetur. Integer dignissim dapibus ligula sed tincidunt. Sed faucibus libero ac venenatis ultrices. Phasellus finibus dolor et tincidunt interdum. Sed sit amet lacus auctor, dignissim libero eget, sagittis nibh. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas.

Nunc ac arcu id ipsum congue convallis vel ac felis. Curabitur a blandit arcu, facilisis vehicula mauris. Morbi scelerisque pharetra mauris id facilisis. Vestibulum odio nisi, euismod a dolor eget, commodo ultricies ipsum. Phasellus vehicula varius eros, vitae consectetur tortor aliquet non. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum gravida urna eget enim faucibus, nec molestie neque efficitur. Nulla faucibus dapibus orci, at ornare neque lacinia vitae. Vestibulum tincidunt rhoncus odio eget dignissim. Suspendisse egestas vitae augue ut dapibus. Nunc eget fringilla libero.
    </div>
</div>

<div class="container">
    <div id="sl-footer-blue">
        <p><a href="#">Accessibility</a> &nbsp;&middot;&nbsp; <a href="#">Terms &amp; Conditions</a> &nbsp;&middot;&nbsp; <a href="#">Privacy</a> &nbsp;&middot;&nbsp; <a href="#">Finance</a> &nbsp;&middot;&nbsp; <a href="#">FAQ</a></p>
    </div>
    <div id="sl-footer-white">
        <p>&copy; Serenity Leisure 2015, Registered in England and Wales. All rights reserved.<br>
        Company registration no. 1234567, Registered office: Pioneer Unit, Station Road, Warmley, Bristol BS30 8XH</p>
    </div>
</div>

<?php //echo $content; ?>

</body>
</html>
