<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
    <?php echo $this->headMeta(); ?>
    <link rel="stylesheet" href="/css/bootstrap.min.css">
    <link rel="stylesheet" href="/css/bootstrap-theme.min.css">
    <link rel="stylesheet" href="/css/sl-frontend.css">
    <link href='https://fonts.googleapis.com/css?family=Bitter:400,700,400italic|Open+Sans:400,700,800,400italic,700italic,800italic' rel='stylesheet' type='text/css'>
    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
    <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
    <script src="/js/jquery-1.11.3.min.js"></script>
    <script src="/js/jquery-ui-1.11.4.min.js"></script>
    <script src="/js/bootstrap-3.3.5.min.js"></script>
    <script src="/js/jquery.ui.touch-punch.min.js"></script>
</head>

<body>

<div class="container">
    <div id="sl-header">
        <div class="col-sm-12 col-md-5 col-lg-4">
            <div class="visible-sm visible-xs sl-logo-spacing">
            </div>
        </div>
        <div class="col-sm-12 col-md-7 col-lg-8">
            <?php echo $this->pageNav(); ?>

            <div class="hidden-xs">
            <h1>0117 967 5577</h1>
            <p>Pioneer Unit &middot; Station Road &middot; Warmley &middot; Bristol &middot; BS30 8XH</p>
            <p>&nbsp;</p>
            </div>
        </div>
    </div>
</div>

<div class="container">
    <?php echo $this->vehicleCategoryNav('motorhomes'); ?>
</div>

<!--
<div class="container">
     <?php //echo $content; ?>
</div>
-->
<div class="container">
<div id="sl-outer-chalk">
    <!--<div id="sl-inner-whiteboard">-->
    <?php echo $content; ?>
    <!--</div>-->
</div>
</div>

<div class="container">
    <div id="sl-footer-blue">
        <?php echo $this->footerNav(); ?>
    </div>
    <div id="sl-footer-white">
        <p>&copy; Serenity Leisure 2016, Registered in England and Wales. All rights reserved.</p>
        <p>Pioneer Unit &middot; Station Road &middot; Warmley &middot; Bristol &middot; BS30 8XH</p>
    </div>
</div>

</body>
</html>
