<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
    <title>Serenity Leisure Control Panel</title>
    <link rel="stylesheet" href="/css/bootstrap.min.css">
    <link rel="stylesheet" href="/css/bootstrap-theme.min.css">
    <link rel="stylesheet" href="//code.jquery.com/ui/1.11.4/themes/smoothness/jquery-ui.css">
    <link rel="stylesheet" href="/css/sl-admin.css">
    <style>
        body {
            /*font-size: 20px;*/
        }
    </style>
    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
    <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->

    <script src="/js/jquery-1.11.3.min.js"></script>
    <script src="/js/jquery-ui-1.11.4.min.js"></script>
    <script src="/js/bootstrap-3.3.5.min.js"></script>
    <script src="/js/jquery.ui.touch-punch.min.js"></script>
</head>

<body>

<nav class="navbar navbar-inverse navbar-fixed-top">
    <div class="container">
        <div id="nav-dashboard" class="navbar-header">
            <a class="navbar-brand" href="/">Dashboard</a>
        </div>

        <div>
            <style type='text/css'>
                ul.nav li.dropdown:hover ul.dropdown-menu {
                    display: block;
                }
            </style>

            <ul class="nav navbar-nav navbar-collapse">
                <li id="nav-vehicles" class="dropdown">
                    <a href="/list-vehicles"><span class="glyphicon glyphicon-road"></span> Vehicles <span class="caret"></span></a>
                    <ul class="dropdown-menu">
                        <li id="nav-add-vehicle"><a href="/add-edit-vehicle"><span class="glyphicon glyphicon-plus"></span> New Vehicle</a></li>
                    </ul>
                </li>

                <li id="nav-collections" class="dropdown">
                    <a href="/list-collections"><span class="glyphicon glyphicon-folder-close"></span> Collections <span class="caret"></span></a>
                    <ul class="dropdown-menu">
                        <li id="nav-add-edit-collection"><a href="/add-edit-collection"><span class="glyphicon glyphicon-plus"></span> New Collection</a></li>
                    </ul>
                </li>

                <li id="nav-upload-images"><a href="/image-uploader"><span class="glyphicon glyphicon-upload"></span> Upload Images</a></li>

                <li id="nav-pages" class="dropdown">
                    <a href="/list-pages"><span class="glyphicon glyphicon-folder-close"></span> Pages <span class="caret"></span></a>
                    <ul class="dropdown-menu">
                        <li id="nav-add-edit-page"><a href="/add-page"><span class="glyphicon glyphicon-plus"></span> New Page</a></li>
                    </ul>
                </li>
            </ul>

            <ul class="nav navbar-nav navbar-collapse pull-right">
                <p class="navbar-text"><span class="glyphicon glyphicon-user"></span> Richard Adams</p>
                <li id="nav-cog" class="dropdown"><a class="dropdown-toggle" data-toggle="dropdown" href="/settings"><span class="glyphicon glyphicon-cog" aria-hidden="true"></span> <span class="caret"></span></a>
                <ul class="dropdown-menu">
                    <li id="nav-cog-settings"><a href="/settings">Settings</a></li>
                    <li id="nav-cog-sign-out"><a href="#">Sign out</a></li>
                </ul>
                </li>
            </ul>
        </div>
    </div>
</nav>

<div class="container"><?php echo $content; ?></div>
</body>
</html>
