<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
    <title>Serenity Leisure Control Panel</title>
    <link rel="stylesheet" href="/css/bootstrap.min.css">
    <link rel="stylesheet" href="/css/bootstrap-theme.min.css">
    <link rel="stylesheet" href="/css/sl-admin.css">
    <style>
        body {
            /*font-size: 20px;*/
        }
    </style>
    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
    <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
    <script src="/js/bootstrap.min.js"></script>
</head>

<body>

<nav class="navbar navbar-inverse">
    <div class="container">
        <div class="navbar-header">
            <a class="navbar-brand" href="/">Serenity Leisure</a>
        </div>

        <div>
            <ul class="nav navbar-nav navbar-collapse">
                <li id="nav-list-vehicles" class="active"><a href="/list-vehicles"><span class="glyphicon glyphicon-road"></span> Vehicles</a></li>
                <li id="nav-add-edit-vehicle"><a href="/add-edit-vehicle"><span class="glyphicon glyphicon-plus"></span> New Vehicle</a></li>
                <li id="nav-collections"><a href="/list-collections"><span class="glyphicon glyphicon-folder-close"></span> Collections</a></li>
                <li id="nav-add-edit-collection"><a href="/add-edit-collection"><span class="glyphicon glyphicon-plus"></span> Collection</a></li>
                <li id="nav-upload-images"><a href="/image-uploader"><span class="glyphicon glyphicon-upload"></span> Upload Images</a></li>
            </ul>

            <ul class="nav navbar-nav navbar-collapse pull-right">
                <p class="navbar-text"><span class="glyphicon glyphicon-user"></span> Richard Adams</p>
                <li id="nav-cog" class="dropdown"><a class="dropdown-toggle" data-toggle="dropdown" href="#"><span class="glyphicon glyphicon-cog" aria-hidden="true"></span> <span class="caret"></span></a>
                <ul class="dropdown-menu">
                    <li id="nav-cog-settings"><a href="#">Settings</a></li>
                    <li id="nav-cog-sign-out"><a href="#">Sign out</a></li>
                </ul>
                </li>
            </ul>
        </div>
    </div>
</nav>

<div class="container"><?php echo $content; ?></div>
</body>
</html>
